name: Create Phar file

on:
  push:
  pull_request:

jobs:
  build:
    name: Create Phar file
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - "8.0"

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.15.0
        with:
          php-version: ${{ matrix.php }}

      - name: Install PHPStan Composer dependencies
        run: composer install --ignore-platform-reqs --no-dev

      - name: Run php-cs-fixer
        run: composer run-script fix-cs
        
      - name: Download ConsoleScript.php
        run: curl -o ../ConsoleScript.php https://raw.githubusercontent.com/pmmp/DevTools/master/src/ConsoleScript.php
        
      - name: Create build folder
        run: mkdir build
        
      - name: Run ConsoleScript.php
        run: php -dphar.readonly=0 ../ConsoleScript.php --make plugin.yml,src,resources,vendor --out build/AdvancedPluginManager.phar
        
      - uses: actions/upload-artifact@v2
        with:
          name: AdvancedPluginManager
          path: build/AdvancedPluginManager.phar
